Sleep Sort Added in JAVA
sukritishah15/DS-Algo-Point pull request #331
Opened 2020-10-03 11:21 UTC by extrathings

## Have you read the Contribution Guidelines?

(Write your answer here.)

## Description

(Write your answer here.)

## Checklist
- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)

Fixes Issue 
<br/>
(Write your answer above.)

2020-10-03 14:20 UTC, sukritishah15 requested changes
Also modify README.md file in Java folder for your added file
Remove the unnecessary files added.
@mephi007 @manan025 @mrjoshi0147 @mahimagoyalx

2020-10-03 14:20 UTC, sukritishah15 commented on Java/SleepSort.java
> +}
At the end of the file add - Sample I/O, Time and Space Complexity in a single multiline comment.

2020-10-03 14:38 UTC, mrjoshi0147 commented
@extrathings Please submit your PR only when your code runs fine. Your code contains some errors. Please have a look at your class and its declaration method. 
  **Note: If you are importing files then add import methods at the top of your code.** 
 First, try to run your code on ide and if it works fine then submit.

2020-10-03 15:01 UTC, mahimagoyalx requested changes
Kindly mention the name of the program at the starting of the program and preferably a small description too in a multi-line comment.

2020-10-03 18:39 UTC, mephi007 requested changes
Please follow Contribution Guidelines before raising PR.
for every issue, you should be creating new branch mentioning issue_id and issue_name.

2020-10-05 08:22 UTC, sukritishah15 commented
@extrathings - Please make ALL the required changes in 3-4 hours.
As we will re-review this PR in 3-4 hours.

Else, we will have to close this PR due to management purposes.

Thank you!

2020-10-06 13:35 UTC, wallacecosta commented
Hi @extrathings , unfortunately their interactions were missing from this pull request so that it could be successfully approved. I appreciate the attempt to contribute and who knows next time will succeed. Have a great week!

2020-10-06 13:35 UTC, closed without merging