Fizz buzz python ds algo
sukritishah15/DS-Algo-Point pull request #371
Opened 2020-10-03 17:03 UTC by shaunak56

## Have you read the Contribution Guidelines?

Yes

## Description

Fizz Buzz is a typical interview question that tests the developer's knowledge of flow control and operators.

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
## Related Issues (Mention Issue no. like #xxx)
#368 

Fixes Issue 
#368 
(Write your answer above.)

2020-10-03 18:55 UTC, sukritishah15 commented on Python/FizzBuzz.py
> +print_fizz_buzz(start_point, end_point)
Add below this Sample I/O, Time and Space Complexity in a multiline comment.

2020-10-03 18:55 UTC, sukritishah15 commented
@shaunak56 - README.md file changes are missing.

2020-10-03 18:58 UTC, mephi007 requested changes
Can you please modify Read.me file too, along with making changes to @sukritishah15's comment.

2020-10-04 04:31 UTC, shaunak56 commented
Sure. I will do the requested changes. Thank you.

2020-10-04 04:59 UTC, closed without merging